cookies:
  bili_jct: ecd8a849628b2b87b5f0eb95dbecf05c
  sessdata: 6c09fdcc%2C1676998160%2C475b3*81
goodnight_words:
- 晚安
- 拜拜
- 别走好吗
- 晚安晚安
- 还会再见吗
- 早点睡吧
- 海比晚安
limited_density: 25
listening_words:
- 晚安
- 拜拜
roomid: 21452505
send_rate: 1.05
